on:
  push:
    branches:
      - main # Trigger the action on push events to your main branch

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror repository
        run: |
          # Clone the main repo
          git clone https://maxwellconsultations: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@github.com/ibeandyy/LBP-Notifier.git

          # Configure git with your info
          git config --global user.email "maxwellconsultations@gmail.com"
          git config --global user.name "maxwellconsultations"

          # Navigate to the repo directory
          cd $(basename ${{ github.repository }})

          # Set the new remote to the organization's repo
          git remote add org_repo https://maxwellconsultations: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@github.com/maxwellconsultations/testRepo.git

          # Push changes to the organization's repo
          git push --mirror org_repo
